# Generated by Django 2.0.3 on 2018-03-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutrecord',
            old_name='user',
            new_name='username',
        ),
    ]
